# Generated by Django 5.0.2 on 2024-02-23 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='feedback',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='message',
            name='ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='session_id',
            field=models.TextField(default=''),
        ),
    ]
