# Generated by Django 5.0.2 on 2024-02-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_app', '0002_message_feedback_message_ratings_message_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='llm_message',
            field=models.TextField(default=''),
        ),
    ]
