# Generated by Django 5.0.2 on 2024-02-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_app', '0004_message_current_response_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='ratings',
        ),
        migrations.AddField(
            model_name='message',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
